package com.s2.otms.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.security.core.context.SecurityContextHolder;
import com.s2.otms.repository.TripRepository;
import com.s2.otms.model.Trips;
import java.util.ArrayList;
import java.util.Arrays;
import com.s2.otms.model.Trip;
import org.springframework.ui.Model;
import org.springframework.web.client.RestTemplate;
import com.s2.otms.security.SslConfiguration;

@Controller    // This means that this class is a Controller
//@RequestMapping(path="/otms") // This means URL's start with /demo (after Application path)
public class OtmsViewController {
	@Autowired // This means to get the bean called tripRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private TripRepository tripRepository;

	@Autowired
    private RestTemplate restTemplate;

	@GetMapping("/triplist.html")
    public String showTripList(Model model) {
        // Here we are returning an object of type 'Trips' rather than a collection of Trip
        // objects so it is simpler for Object-Xml mapping
		Trips trips = new Trips();
		String currentUserName = SecurityContextHolder.getContext().getAuthentication().getName();
		// if admin user, return all the trip records
		if("admin".equalsIgnoreCase(currentUserName)) {
			trips.getTripList().addAll(tripRepository.findAll());
		} else {
        	// if an ordinary user, return only the trip records of the logged in employee
			int empId=Integer.parseInt(currentUserName);
			trips.getTripList().addAll(tripRepository.findByEmpId(empId));
		}
        model.addAttribute("trips", trips);
        return "trips";
	}
	
	@GetMapping("/trips.html")
	public String showTripListRest(Model model) {
     	Trip[] trips;
		Trips tripList = new Trips();
		
		String currentUserName = SecurityContextHolder.getContext().getAuthentication().getName();
		String url = "https://localhost:8443/trips?user=" + currentUserName;
		trips = restTemplate.getForObject(url, Trip[].class);
		
		ArrayList<Trip> arrayList = new ArrayList<Trip>(Arrays.asList(trips));
		tripList.getTripList().addAll(arrayList);
		
		model.addAttribute("trips", tripList);
        return "trips";
	}

	@GetMapping({"/home", "/"})
    public String showHome(Model model) {
        return "home";
	}
	
	@GetMapping("/login")
    public String showLogin(Model model) {
        return "login";
    }
}

