package otms.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.security.core.context.SecurityContextHolder;
import otms.repository.TripRepository;
import otms.model.Trips;
import org.springframework.ui.Model;


@Controller    // This means that this class is a Controller
//@RequestMapping(path="/otms") // This means URL's start with /demo (after Application path)
public class OtmsViewController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private TripRepository tripRepository;

	@GetMapping("/trips.html")
    public String showTripList(Model model) {
        // Here we are returning an object of type 'Trips' rather than a collection of Trip
        // objects so it is simpler for Object-Xml mapping
		Trips trips = new Trips();
		String currentUserName = SecurityContextHolder.getContext().getAuthentication().getName();
		// if admin user, return all the trip records
		if("admin".equalsIgnoreCase(currentUserName)) {
			trips.getTripList().addAll(tripRepository.findAll());
		} else {
        	// if an ordinary user, return only the trip records of the logged in employee
			int empId=Integer.parseInt(currentUserName);
			trips.getTripList().addAll(tripRepository.findByEmpId(empId));
		}
        model.addAttribute("trips", trips);
        return "trips";
	}
	
	@GetMapping({"/home", "/"})
    public String showHome(Model model) {
        return "home";
	}
	
	@GetMapping("/login")
    public String showLogin(Model model) {
        return "login";
    }
}
